# Generated by Django 4.1.2 on 2022-10-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_employee_emp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='webportal',
            field=models.URLField(default='www.google.com'),
        ),
    ]
