# Generated by Django 4.1.2 on 2022-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_company', models.CharField(max_length=25)),
                ('emp_address', models.TextField()),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
