# Generated by Django 4.1.2 on 2022-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField(verbose_name='Employee Code')),
                ('emp_name', models.CharField(max_length=20, verbose_name='Employee Name')),
                ('emp_company', models.CharField(max_length=25, verbose_name='Employee Company Name')),
                ('emp_address', models.TextField(default='xyz', verbose_name='Employee Address')),
                ('emp_salary', models.IntegerField(verbose_name='Employee Current Salary')),
                ('group', models.BooleanField(default=True)),
                ('joining_date', models.DateField()),
                ('joining_date_time', models.DateTimeField()),
            ],
        ),
    ]
