# Generated by Django 4.1.2 on 2022-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
                ('emp_code', models.CharField(max_length=10)),
                ('joining_date', models.DateTimeField()),
                ('address', models.TextField()),
            ],
        ),
    ]
